"""
SkyResQ AI Config Package
"""

from ai.config.settings import (
    DEFAULT_MODEL_NAME,
    DEFAULT_MODEL_PATH,
    YOLO_MODEL_PATH,
    DEFAULT_CONFIDENCE_THRESHOLD,
    DEFAULT_CONF_THRESHOLD,
    DEFAULT_IOU_THRESHOLD,
    ALLOWED_IMAGE_EXTENSIONS,
    MAX_IMAGE_SIZE_BYTES,
    DETECTIONS_API_ENDPOINT,
    COCO_CLASS_MAPPINGS,
    COCO_SAR_MAPPINGS,
    PERSON_CLASS_NAMES,
    HAZARD_CLASS_NAMES,
    SUPPORTED_SOURCES,
    MODELS_DIR,
    SAR_TARGET_CLASS_IDS,
    CLASS_NAME_MAPPINGS,
    format_class_name
)

__all__ = [
    "DEFAULT_MODEL_NAME",
    "DEFAULT_MODEL_PATH",
    "YOLO_MODEL_PATH",
    "DEFAULT_CONFIDENCE_THRESHOLD",
    "DEFAULT_CONF_THRESHOLD",
    "DEFAULT_IOU_THRESHOLD",
    "ALLOWED_IMAGE_EXTENSIONS",
    "MAX_IMAGE_SIZE_BYTES",
    "DETECTIONS_API_ENDPOINT",
    "COCO_CLASS_MAPPINGS",
    "COCO_SAR_MAPPINGS",
    "CLASS_NAME_MAPPINGS",
    "PERSON_CLASS_NAMES",
    "HAZARD_CLASS_NAMES",
    "SUPPORTED_SOURCES",
    "MODELS_DIR",
    "SAR_TARGET_CLASS_IDS",
    "format_class_name"
]
